org: josueespinoza
service: espe-serverless

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:*
    Resource:
    - arn:aws:dynamodb:us-east-1:205930610423:table/TaskTable

functions:
  hello:
    handler: src/handler.hello
    events:
    - httpApi:
        path: /
        method: get
  createTask:
    handler: src/addTask.addTask
    events:
    - httpApi:
        path: /task
        method: post
  getTasks:
    handler: src/getTask.getTask
    events:
    - httpApi:
        path: /task
        method: get
  updateTask:
    handler: src/updateTask.updateTask
    events:
    - httpApi:
        path: /task/{id}
        method: put

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
   